# These are supported funding model platforms

github: [ansidev]
patreon: ansidev
# open_collective: # Replace with a single Open Collective username
ko_fi: ansidev
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom:
  - "https://www.paypal.me/ansidev"
  - "https://www.buymeacoffee.com/ansidev"
  - "https://me.momo.vn/ansidev"
