name: deploy_production

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_NAME: ${{ vars.NETLIFY_SITE_NAME }}
  DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy_netlify.outputs.netlify-deploy-url }}
    steps:
      - name: Build site
        id: build
        uses: ghacts/static-site@main
        env:
          DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}
          DOCSEARCH_API_KEY: ${{ secrets.DOCSEARCH_API_KEY }}
          DOCSEARCH_INDEX_NAME: ${{ secrets.DOCSEARCH_INDEX_NAME }}
          GA_ID: ${{ secrets.GA_ID }}
        with:
          node-version: 20
          skip-test: true
          output-dir: ${{ env.DEPLOY_DIR }}

      - name: Deploy to GitHub Pages
        if: always() && steps.build.outcome == 'success'
        id: deploy_github
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: ${{ env.DEPLOY_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy to Netlify
        if: always() && steps.build.outcome == 'success'
        id: deploy_netlify
        uses: ghacts/manual-deploy-to-netlify@main
        with:
          auth-token: ${{ env.NETLIFY_AUTH_TOKEN }}
          site: ${{ env.NETLIFY_SITE_NAME }}
          dir: ${{ env.DEPLOY_DIR }}
          prod: true
